apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: www-redirect
  name: www-redirect
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: www-redirect
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - periodSeconds: 300
        type: Percent
        value: 100
